module.exports = {
  CORRECT_ALERT: '真棒！',
  INCORRECT_ALERT: '繼續努力！',
  SOME_EXCEPTION: '喔唷，挂了！',
  CLICK_BLANK_FIRST: '先把选好的字母填入空格！',
  FINISH_ALL_QUESTIONS: '全部完成！',
  CONFIRM_TITLE: '确认信息',
  SIGNOUT_CONFIRM_MSG: '你确认要登出吗？',
  CONFIRM_RESET_MSG: '真的要重来吗？',
  CONFIRM_FINISHED_MSG: '恭喜你，完成了！要重来一遍么？',
  FEATURE_IS_DISABLE: '该功能暂时无法使用',
  ON_LOADING: '努力加载中',
  NO_MEANING: '找不到解释呀！',
  SELECT_SOME_TAG: '请选择至少一个标签。',
}